config/routes.rb
Equipmentroom::Application.routes.draw do
  resources :equipment

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :about
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = Equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= form_for(@equipment) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_field :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<h1 align="center"> Equipment room</h1>
<table align="center">
<tr ><th>รายชื่อสมาชิก</th></tr>
<tr align="left"><th>นาย วรุฒ </th><th>ไพศาลสมสุข</th><th>5310611115</th></tr>
<tr align="left"><th>นาย คุณานนต์</th><th>คารวะชนะภัย</th><th>5310611222</th></tr>
<tr align="left"><th>นางสาว กิตติพร</th><th>พิพัฒน์เจษฎากุล</th><th>5310611321</th></tr>
<tr align="left"><th>นาย กันต์ศักดิ์ </th><th>ด่านขจร</th><th>5310612683</th></tr>
</table>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>ความต้องการของลูกค้า(Requirements)</b><br><ul>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลูกค้าต้องการให้ผู้ยืมอุปกรณ์สามารถกรอกรายละเอียดการยืมได้<br></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลูกค้าต้องการให้สามารถตรวจสอบรายละเอียดการยืมอุปกรณ์ได้<br></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลูกค้าต้องการให้ผู้ยืมสามารถต่อเวลาการยืมอุปกรณ์<br></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลูกค้าต้องการให้ลดขั้นตอนการส่งคืนอุปกรณ์<br></li><br>
<b>Applicationช่วยแก้ปัญหา(Benefit)</b><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลูกค้าไม่ต้องเก็บเอกสารการยืมที่เป็นกระดาษ ทำให้ง่ายต่อการจัดเก็บและลดขั้นตอนการยืม<br></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลูกค้าสามารถตรวจสอบรายละเอียดการยืมอุปกรณ์ได้ง่ายมากขึ้น ตรวจสอบรายละเอียดการยืมได้ง่าย<br></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลดการสูญหายของอุปกรณ์และการขาดแคลนอุปกรณ์<br></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<li>ลดขั้นตอนในการส่งคืนอุปกรณ์จากผู้ยืมกับลูกค้า<br></li><br>
<b>ผู้มีส่วนได้ส่วนเสีย(stakeholders)</b><br><br>
<li>นักศึกษา<br></li>
<li>อาจารย์<br></li>
<li>เจ้าหน้าที่ดูแลห้องพัสดุ อุปกรณ์<br></li></ul>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<h2><b>User story</h2></b>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Borrow a device<br><br></b>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As a Teacher and Student<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So that I can borrow some device<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I want to get the information to borrowing device<br><br><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Return a device<br><br></b>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As a Teacher and Student<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So that I can return device<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I want to return device
<br><br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Renew a device<br><br></b>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As a Teacher and Student<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So that I can can renew device<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I want to renew device<br><br><br>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Search a borrower information<br><br></b>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As a Teacher and Student<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So that I can search the information of borrower<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I want to get the information of borrower<br><br>

<h2 align="center">Lofi<BR>
<%= image_tag("1.JPG") %><bR>
<%= image_tag("2.jpg") %><bR>
Storyboards<BR>
<%= image_tag("3.jpg") %><bR>
 ER diagram <BR>
<%= image_tag("ER.png") %>
</h2>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>About:</b>
  <%= @equipment.about %>
</p>


<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Equipmentroom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>